# Site settings
author: William Zimmerman
title: William Zimmerman's Blog
header-img: img/home-bg.png
email: william.a.zimmerman+learn@gmail.com
copyright_name: William Zimmerman
description: > # this means to ignore newlines until "baseurl:"
  My coding blog
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  wazimmerman

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
